export const SITE = {
  website: "https://www.gaultonlab.org/",
  author: "Kyle Gaulton",
  profile: "https://github.com/orgs/Gaulton-Lab",
  desc: "A biomedical research group at UC San Diego studying gene regulation, epigenomics, and the genetic basis of type 1 diabetes and other complex diseases.",
  title: "The Gaulton Lab",
  ogImage: "devosfera-og.webp",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 12,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showGalleries: false,
  showGalleriesInIndex: false,
  showBackButton: true,
  showTagsInCards: false,
  showCoverImages: false,
  indexPostsGrid: false,
  heroTerminalPrompt: {
    prefix: "~",
    path: "/gaultonlab",
    suffix: "$",
  },
  backdropEffects: {
    cursorGlow: true,
    grain: true,
  },
  editPost: {
    enabled: false,
    text: "Edit this post",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/Los_Angeles",
  introAudio: {
    enabled: false,
    src: "",
    isStream: false,
    label: "",
    duration: 30,
  },
} as const;